name: Collect

on:
  workflow_dispatch:

  push:
    paths:
      - "./EternityBase"
      - "./sub/sub_merge_base64.txt"
      - "./sub/sub_merge_yaml.yml"

  schedule:
    - cron: "0 0,12 * * *"

jobs:
  main:
    name: Collect & SpeedTest & Filter
    runs-on: ubuntu-latest
    # runs-on: ubuntu-24.04
    #timeout-minutes: 90
    steps:
    
      - uses: actions/checkout@v5.0.0
      
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.11.14"
          
      - name: Clean working directory
        run: |
          git clean -fd
          git reset --hard
          
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'
      - name: Install Requirements
        run: |

          pip install --upgrade pip
          pip install -r ./utils/requirements.txt

      - name: Running Collector
        run: |
          wget -O subconverter.tar.gz https://github.com/Airuop/cross/raw/refs/heads/master/utils/download/subconverter/releases/v0.9.0/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          node ./utils/localserver/index.js &
          sleep 2
          python ./utils/list_merge.py
          
      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add ./sub
          git add ./utils/Country.mmdb
          git add README.md
          git checkout master
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
          git push --force

      - name: Run Lite Speedtest
        run: |
          sleep 5
          sudo sh ./utils/speedtest/speedtest2_yaml.sh
          sleep 5
          python ./utils/speedtest/output.py
          
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add EternityBase
          git add Eternity
          git add Eternity.txt
          git add ./sub/sub_merge.txt
          git add ./sub/sub_merge_base64.txt
          git add LogInfo.txt
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Tested"
          git push --force
      

      - name: Run Convertor & Formatter
        run: |
          sleep 5
          wget -O subconverter.tar.gz https://github.com/Airuop/cross/raw/refs/heads/master/utils/download/subconverter/releases/v0.9.0/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          python ./utils/eternity_convert.py
          
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add Eternity.yml
          git add Eternity
          git add ./update/*
          git add LogInfo.txt
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Filtered"
          git push --force
      
